# Generated by Django 2.1 on 2019-02-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlRpi',
        ),
    ]
